### ISSUE TITLE
Could you release a new version please?

### ISSUE THREAD

**Issue by jaqx0r** [linas/glextrusion#10]
Hi!  I'm the Debian package maintainer and having some trouble with the old autoconf files against the current Debian autoconf tool versions.  I see you fixed all these problems a few years back.

I'm attempting to roll the patches into the Debian package on top of 3.1.0, but it'd be very helpful if you could tag and release a new version with all the changes since 3.1.0.

Thanks in advance!

**Comment by jaqx0r** [comment]
I only just noticed that
https://github.com/linas/glextrusion/blob/fb75bfce1632cdde2c17ab5083384f1dcabb8ba2/configure.ac#L26 is a new version!

The release isn't tagged as such, though, and we don't have new tarballs.  I'm going to proceed assuming I can use commit https://github.com/linas/glextrusion/commit/fb75bfce1632cdde2c17ab5083384f1dcabb8ba2 as the 3.1.1 release.  If you can please tag this commit with a version or Github Release tag that'd be great please.

**Comment by linas** [comment]
I just did a `git tag -s gle-3.1.1` and so it's now tagged and GPG-signed.  Anything else I'm forgetting?

**Comment by jaqx0r** [comment]
That's perfect, thanks!
