### ISSUE TITLE
`src/Makefile.am` is missing `LIBADD` for dependent libraries

### ISSUE THREAD

**Issue by jaqx0r** [linas/glextrusion#11]
`configure.ac` checks for and appends required libraries to the `@X_LIBS@` variable, and then uses that in `examples/Makefile.am`'s `LDADD`, which is great for compiling the examples in-project.

But the generated `libgle.so.3.1.0` does not link with `@X_LIBS@` and so `ldd src/.libs/libgle.so.3.1.0` is missing dependency information on libGL, libGLU, libglut, etc.

This manifests as link-time errors:

`gcc -o test test.c -lgle`:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libgle.so: undefined reference to `gluNewTess'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libgle.so: undefined reference to `gluTessVertex'
```

(actual example code:  https://salsa.debian.org/debian/gle/-/blob/debian/debian/tests/build   and build log: https://salsa.debian.org/debian/gle/-/jobs/4572587 )

Putting all of `@X_LIBS@` into `src/Makefile.am`'s `libgle_la_LIBADD` is almost correct, except that configure.ac also inserts `-lgle` in `X_LIBS`.   https://github.com/linas/glextrusion/blob/fb75bfce1632cdde2c17ab5083384f1dcabb8ba2/configure.ac#L141

I think a fix could be to stop inserting `-lgle` into `X_LIBS`, using `X_LIBS` to set `libgle_la_LIBADD` in `src/Makefile.am`, and inserting -lgle in only the examples/Makefile.am LIBADD variable.

**Comment by linas** [comment]
Should the version number be bumped?

**Comment by jaqx0r** [comment]
I don't need it to be -- up to you.

**Comment by linas** [comment]
I also just now fixed a bunch of compiler warnings. So I bumped the version number. And gat-tagged it too. I's now 3.1.2

**Comment by linas** [comment]
Anyway, thanks for the patch!

**Comment by jaqx0r** [comment]
No worries!
